Repository RediSearch/redisearch-go, pull requests merged in 2020-05, with the labels that each got.

#70 support for [TEMPORARY {seconds}] on FT.CREATE
  .circleci/config.yml
  Makefile
  examples/quickstart/quickstart.go
  examples/temporary/temporary.go
  redisearch/client_test.go
  redisearch/example_schema_test.go
  redisearch/schema.go
  redisearch/schema_test.go
Labels: documentation, enhancement

#68 Addition of examples on documentation for NewClient and NewClientFromPool
  .circleci/config.yml
  .gitignore
  Makefile
  examples/redisearch_auth/redisearch_auth.go
  examples/redisearch_quickstart/redisearch_quickstart.go
  examples/redisearch_tls_client/redisearch_tls_client.go
  redisearch/client.go
  redisearch/example_client_test.go
  redisearch/package.go
  redisearch/redisearch_test.go
Labels: documentation

#72 Support for INFIELDS
  redisearch/query.go
  redisearch/query_test.go
Labels: enhancement
