Repository RediSearch/redisearch-go, pull requests merged in 2021-04, with the labels that each got.

#103 add a fun<List> to support FT._LIST
  redisearch/client.go
  redisearch/client_test.go
Labels: enhancement

#97 Added support for SLOP
  redisearch/query.go
Labels: state:needs-test-pr

#104 Added example to demonstrate use georadius.
  .gitignore
  Makefile
  examples/redisearch_geo/redisearch_geo.go
  go.mod
  go.sum
  redisearch/example_client_test.go
Labels: enhancement

#107 Added support for hash_indexing_failures on Info() wrapper
  redisearch/client_test.go
  redisearch/index.go
Labels: enhancement

#108 Fixed flaky TestClient_ListIndex()
  redisearch/client_test.go
Labels: bug
