Repository RediSearch/redisearch-go, pull requests merged in 2021-08, with the labels that each got.

#124 some documentations
  redisearch/aggregate.go
  redisearch/autocomplete.go
  redisearch/client.go
  redisearch/document.go
  redisearch/index.go
  redisearch/query.go
  redisearch/spellcheck.go
Labels: documentation

#125 support NOHL and SKIPINITIALSCAN tags on FT.CREATE
  redisearch/schema.go
  redisearch/schema_test.go
Labels: enhancement

#126 go 1.16
  .circleci/config.yml
  go.mod
  go.sum
Labels: skip-changelog
